swagger: '2.0'
info:
  title: OSF APIv2 Documentation
  version: '2.0'
  description: >-
    Welcome to the documentation for the Open Science Framework API. With this
    API you can access users, projects, components, registrations, preprints,
    logs, and files on the Open Science Framework.
  contact:
    name: OSF
    email: support@osf.io
    url: 'https://osf.io/support'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8000'
basePath: /v2
paths:

  ####################
  #   INTRODUCTION   #
  ####################

  # These are fake enpoints used for sidebar documentation
  /introduction/:
    $ref: 'introduction/introduction.yaml'

  /general_api_usage/:
    $ref: 'introduction/general_api_usage.yaml'

  /versioning/:
    $ref: 'introduction/versioning.yaml'

  /filtering_and_embedding/:
    $ref: 'introduction/filtering_and_embedding.yaml'

  /pagination/:
    $ref: 'introduction/pagination.yaml'

  /put_patch_requests/:
    $ref: 'introduction/put_patch_requests.yaml'

  /attribute_validation/:
    $ref: 'introduction/attribute_validation.yaml'

  /entities/:
    $ref: 'introduction/entities.yaml'

  /entity_collections/:
    $ref: 'introduction/entity_collections.yaml'

  /errors/:
    $ref: 'introduction/errors.yaml'

  /osf_enum_fields/:
    $ref: 'introduction/osf_enum_fields.yaml'

############
#   BASE   #
############

  /:
    get:
      description: ''
      summary: Root
      responses:
        '200':
          description: OK
      tags:
        - Base
      operationId: base_read

#################
#   PREPRINTS   #
#################

  /preprints/:
    $ref: 'preprints/list.yaml'

  /preprints/{preprint_id}/:
    $ref: 'preprints/detail.yaml'

#########################
#   MODEL DEFINITIONS   #
#########################

definitions:
  Preprint:
    $ref: 'preprints/definition.yaml'

securityDefinitions:
  basic:
    type: basic
