swagger: '2.0'
info:
  title: OSF APIv2 Documentation
  version: '2.0'
  description: >-
    Welcome to the documentation for the Open Science Framework API. With this
    API you can access users, projects, components, registrations, preprints,
    logs, and files on the Open Science Framework.
  contact:
    name: OSF
    email: support@osf.io
    url: 'https://osf.io/support'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'test-api.osf.io'
schemes:
  - https
basePath: /v2
paths:

  ####################
  #   INTRODUCTION   #
  ####################

  # These are fake enpoints used for sidebar documentation
  /introduction/:
    $ref: 'introduction/introduction.yaml'

  /general_api_usage/:
    $ref: 'introduction/general_api_usage.yaml'

  /entities/:
    $ref: 'introduction/entities.yaml'

  /entity_collections/:
    $ref: 'introduction/entity_collections.yaml'

  /osf_enum_fields/:
    $ref: 'introduction/osf_enum_fields.yaml'

  /filtering/:
    $ref: 'introduction/filtering.yaml'

  /embedding/:
    $ref: 'introduction/embedding.yaml'

  /put_patch_requests/:
    $ref: 'introduction/put_patch_requests.yaml'

  /attribute_validation/:
    $ref: 'introduction/attribute_validation.yaml'

  /errors/:
    $ref: 'introduction/errors.yaml'

  /error_codes/:
    $ref: 'introduction/error_codes.yaml'

  /pagination/:
    $ref: 'introduction/pagination.yaml'

  /versioning/:
    $ref: 'introduction/versioning.yaml'

  ############
  #   BASE   #
  ############

  /:
    get:
      summary: Root
      description: >-
        Welcome to the Open Science Framework API. With this API you can access
        users, projects, components, logs, and files from the [Open Science
        Framework](https://osf.io/). The Open Science Framework (OSF) is a free,
        open-source service maintained by the [Center for Open
        Science](http://cos.io/).


        #### Returns

        A JSON object with `meta` and `links` keys.


        The `meta` key contains information such as a welcome message from the API, the specified version of the request,
        and the full representation of the current user, if authentication credentials were provided in the request.


        The `links` key contains links to the following entity collections: [addons](), [collections](),
        [institutions](#Institutions_institutions_list), [licenses](#Licenses_license_list), [metaschemas](),
        [nodes](#Nodes_nodes_list), [registrations](), [users](#Users_users_list)

      responses:
        '200':
          description: OK
      tags:
        - Base
      operationId: base_read

  #################
  #   CITATIONS   #
  #################

  /citations/styles/:
    $ref: 'citations/style_list.yaml'

  /citations/styles/{style_id}/:
      $ref: 'citations/style_detail.yaml'

  ################
  #   COMMENTS   #
  ################

  /comments/{comment_id}/:
    $ref: 'comments/detail.yaml'

  # /comments/{comment_id}/reports/:
  #   $ref: 'comments/reports_list.yaml'

  # /comments/{comment_id}/reports/{user_id}/:
  #   $ref: 'comments/report_detail.yaml'

  #############
  #   FILES   #
  #############

  /files/{file_id}/:
    $ref: 'files/detail.yaml'

  /files/{file_id}/versions/:
    $ref: 'files/versions_list.yaml'

  /files/{file_id}/versions/{version_id}/:
    $ref: 'files/version_detail.yaml'

  #################
  #    LICENSES   #
  #################

  /licenses/:
    $ref: 'licenses/list.yaml'

  /license/{license_id}/:
    $ref: 'licenses/detail.yaml'

  ############
  #   LOGS   #
  ############

  /logs/{log_id}/:
    $ref: 'logs/detail.yaml'

  # this is a fake endpoint for sidebar documentation
  /actions/:
    $ref: 'logs/actions.yaml'

  ####################
  #   INSTITUTIONS   #
  ####################

  /institutions/:
    $ref: 'institutions/list.yaml'

  /institutions/{institution_id}/:
    $ref: 'institutions/detail.yaml'

  /institutions/{institution_id}/users/:
    $ref: 'institutions/users_list.yaml'

  /institutions/{institution_id}/nodes/:
    $ref: 'institutions/nodes_list.yaml'

  /institutions/{institution_id}/registrations/:
    $ref: 'institutions/registrations_list.yaml'

  # /institutions/{institution_id}/relationships/nodes/:
  #   $ref: 'institutions/nodes_relationships.yaml'

  #############
  #   NODES   #
  #############

  /nodes/:
    $ref: 'nodes/list.yaml'

  /nodes/{node_id}/:
    $ref: 'nodes/detail.yaml'

  /nodes/{node_id}/children/:
    $ref: 'nodes/children_list.yaml'

  /nodes/{node_id}/citation/:
    $ref: 'nodes/citation_detail.yaml'

  /nodes/{node_id}/citation/{style_id}/:
    $ref: 'nodes/styled_citation_detail.yaml'

  /nodes/{node_id}/contributors/:
    $ref: 'nodes/contributors_list.yaml'

  /nodes/{node_id}/contributors/{user_id}/:
    $ref: 'nodes/contributor_detail.yaml'

  /nodes/{node_id}/draft_registrations/:
    $ref: 'nodes/draft_registrations_list.yaml'

  /nodes/{node_id}/draft_registrations/{draft_id}/:
    $ref: 'nodes/draft_registration_detail.yaml'

  /nodes/{node_id}/forks/:
    $ref: 'nodes/forks_list.yaml'

  /nodes/{node_id}/wikis/:
    $ref: 'nodes/wikis_list.yaml'

  /nodes/{node_id}/preprints/:
    $ref: 'nodes/preprints_list.yaml'

  /nodes/{node_id}/comments/:
    $ref: 'nodes/comments_list.yaml'

  /nodes/{node_id}/files/:
    $ref: 'nodes/providers_list.yaml'

  /nodes/{node_id}/institutions/:
    $ref: 'nodes/institutions_list.yaml'

  /nodes/{node_id}/linked_nodes/:
    $ref: 'nodes/linked_nodes_list.yaml'

  #################
  #   PREPRINTS   #
  #################

  /preprints/:
    $ref: 'preprints/list.yaml'

  /preprints/{preprint_id}/:
    $ref: 'preprints/detail.yaml'

  /preprints/{preprint_id}/citation/:
    $ref: 'preprints/citation_detail.yaml'

  /preprints/{preprint_id}/citation/{style_id}/:
    $ref: 'preprints/citation_style_detail.yaml'


  ##########################
  #   PREPRINT PROVIDERS   #
  ##########################

  /preprint_providers/:
    $ref: 'preprint_providers/list.yaml'

  /preprint_providers/{preprint_provider_id}/:
    $ref: 'preprint_providers/detail.yaml'

  /preprint_providers/{preprint_provider_id}/preprints/:
    $ref: 'preprint_providers/preprints_list.yaml'

  /preprint_providers/{preprint_provider_id}/taxonomies/:
    $ref: 'preprint_providers/taxonomies_list.yaml'

  /preprint_providers/{preprint_provider_id}/licenses/:
    $ref: 'preprint_providers/licenses_list.yaml'

  #####################
  #   REGISTRATIONS   #
  #####################

  /registrations/:
    $ref: 'registrations/list.yaml'

  /registrations/{registration_id}/:
    $ref: 'registrations/detail.yaml'

  #############
  #   USERS   #
  #############

  /users/:
    $ref: 'users/list.yaml'

  /users/{user_id}/:
    $ref: 'users/detail.yaml'

  /users/{user_id}/institutions/:
    $ref: 'users/institutions_list.yaml'

  /users/{user_id}/nodes/:
    $ref: 'users/nodes_list.yaml'

  /users/{user_id}/preprints/:
    $ref: 'users/preprints_list.yaml'

  /users/{user_id}/registrations/:
    $ref: 'users/registrations_list.yaml'

  #############
  #   WIKIS   #
  #############

  /wikis/{wiki_id}/:
    $ref: 'wikis/detail.yaml'

  /wikis/{wiki_id}/content/:
    $ref: 'wikis/content.yaml'
